#+TITLE: FMA/AAWM and ICMPC/ESCOM


#+DATE: <2018-08-10 Fri> 



Short update. Just attended and presented at these conferences in the summer:

The 8th International Workshop on Folk Music Analysis/Fifth International Conference on Analytical Approaches to World Music (AAWM 2018):  http://fma2018.mus.auth.gr

Paper: Feature analysis of repeated patterns in Dutch folk songs using Principal Component Analysis (Iris Yuping Ren, Hendrik Vincent Koops, Dimitrios Bountouridis, Anja Volk, Wouter Swierstra and Remco Veltkamp)

Slides: https://goo.gl/NrhFzf

15th International Conference on Music Perception and Cognition/10th triennial conference of the European Society for the Cognitive Sciences of Music: https://music-psychology-conference2018.uni-graz.at/en/

Paper: Investigating Musical Pattern Ambiguity in a Human Annotated Dataset (Iris Yuping Ren, Oriol Nieto, Hendrik Vincent Koops, Anja Volk, Wouter Swierstra)

Slides: https://goo.gl/S3n51X

I had a very good experience with all four conferences. This is my third time to FMA, but the rest are all new to me. There were a variety of audience, talks and posters. It’s amazing how people from different fields come together and talk about a diverse range of topics related to music.

What is the most valuable is the intellectual stimulation from seeing new research results, discussing how we have been doing research (on different and similar topics), connecting with a larger community, reflecting and planning on my own research, etc.

A big thank you to all the old friends and new friends, it was very nice seeing you there. Next time is ISMIR in September. See you in Paris 🙂
